const open = document.getElementById('open')
const close = document.getElementById('close')
const section = document.querySelector('section')
const container = document.querySelector('.container')
open.addEventListener('click', () => section.classList.add('show-nav'))
close.addEventListener('click', () => section.classList.remove('show-nav'))
open.addEventListener('click', () => container.classList.add('show-nav'))
close.addEventListener('click', () => container.classList.remove('show-nav'))